create table tb_author (id int8 generated by default as identity, email varchar(255), name varchar(255), primary key (id));
create table tb_newsletter (reader_id int8 not null, email varchar(255), primary key (reader_id));
create table tb_notices (id int8 generated by default as identity, notice varchar(255), post_date timestamp, title varchar(255), author_id int8 not null, primary key (id, author_id));
create table tb_reader (id int8 generated by default as identity, email varchar(255), name varchar(255), primary key (id));
alter table if exists tb_newsletter add constraint FK23yhb6qop0f6hnb72hcorm3cv foreign key (reader_id) references tb_reader;
alter table if exists tb_notices add constraint FKl8lgmbrjoav0thqqtqx6vrr4k foreign key (author_id) references tb_author;

